config/routes.rb
BrainsUniversity::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :videos, only: [:index, :new, :create, :show]
  resources :comments, :only => [:create, :destroy]
  
  scope :module => "materias" do
    get 'materias', to: 'materias#index', as: '/materias'
    
    resources :estatica, only: [:index] do
      collection do
        get 'equilibrio_cuerpos_rigidos'
      end
    end
    
    resources :termodinamica, only: [:index]
  end

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/users',   to: 'users#show',           via: 'get'
  match '/videos',  to: 'user#index',           via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/landing', to: 'static_pages#landing', via: 'get'
  match '/home',    to: 'static_pages#home', via: 'get'
  

  get "videos/:id/doubts" => 'videos#doubts', :as => :doubts
  post "videos/doubts_mail" => 'videos#doubts_mail', :as => :doubts_mail
  match '/contact',  to: 'static_pages#create',        via: 'post'

  root 'static_pages#home'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates :name,  presence: true, length: { maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, 
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false}
	has_secure_password										
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:show, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        flash[:success] = "Welcome to the Sample App!"
        format.html { redirect_to edit_user_path(@user), notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = "El usuario fue actualizado satisfactoriamente"
        format.html { redirect_to edit_user_path(@user)}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      set_user
      redirect_to(root_url) unless current_user?(@user)
    end

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end


end

app/helpers/users_helper.rb
module UsersHelper

def gravatar_for(user)
	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
 end
  
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <div class="form-inputs">
    <%= f.input :name,  label: false, requiered: true, placeholder: 'Nombre'%>
    <%= f.input :email, label: false, requiered: true, :autofocus => true, placeholder: 'Correo' %>
    <%= f.input :password, placeholder: 'Contraseña', label: false %>
  	<%= f.input :password_confirmation, placeholder: 'Confirmar Contraseña', label: false%>
  </div>
  
  <% if signed_in? %>
    <%= f.button :submit, "Actualizar" , class: "btn btn-primary btn-lg"%>
  <% else %>
    <%= f.button :submit, "Registrarse" , class: "btn btn-primary btn-lg"%> 	
  <% end %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Editar Usuario") %>
<div class="sign-in-page row">
	<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
	<div class="container">
		<div class="sign-forms sign-up">
  		<div class="row">
  			<%= render 'shared/error_messages', :object => @user%>
      	<h1 class="top-margin"> <%= @user.name %> </h1>
    		<h1 class="image-avatar">
      		<img src="<%= gravatar_for @user %>" alt="<%= @user.name %>" class='gravatar'>
    		</h1>
    		<h1 class="change-avatar"><a href="http://gravatar.com/emails">change</a></h1> 
	      	
				<%= render "form" %>
	  	</div>	
  	</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="sign-in-page row">
  <div class="container sign-forms sign-up">
    <div>
      <%= render 'shared/error_messages', object: @user %>
      <h1>Regístrate</h1>

      <%= render "form" %>
      
    </div>
    <div class="link-sign-in">
      <label>¿Ya tienes cuenta? <%= link_to "¡Ingresa ya!", signin_path %></label>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container profile">
	<div class="row">
	  <aside class="span4">
	    <section>
	    	<h1>
	    		<img src="<%= gravatar_for @user %>" alt="<%= @user.name %>" class='gravatar'>
	    		<%= @user.name %>
				</h1>
	    </section>
	  </aside>
	  <%= link_to 'Edit', edit_user_path(@user) %> |
		<%= link_to 'Back', users_path %>
	</div>

	
</div>