config/routes.rb
BrainsUniversity::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :videos, only: [:index, :new, :create, :show]
  resources :comments, :only => [:create, :destroy]
  
  scope :module => "materias" do
    get 'materias', to: 'materias#index', as: '/materias'
    
    resources :estatica, only: [:index] do
      collection do
        get 'equilibrio_cuerpos_rigidos'
      end
    end
    
    resources :termodinamica, only: [:index]
  end

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/users',   to: 'users#show',           via: 'get'
  match '/videos',  to: 'user#index',           via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/landing', to: 'static_pages#landing', via: 'get'
  match '/home',    to: 'static_pages#home', via: 'get'
  

  get "videos/:id/doubts" => 'videos#doubts', :as => :doubts
  post "videos/doubts_mail" => 'videos#doubts_mail', :as => :doubts_mail
  match '/contact',  to: 'static_pages#create',        via: 'post'

  root 'static_pages#home'

  

end

app/models/video.rb
class Video < ActiveRecord::Base

	acts_as_commentable
	validates :subject,  presence: true, length: { maximum: 30}
	YT_LINK_FORMAT = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
 	validates :link, presence: true, format: { with: YT_LINK_FORMAT, multiline: true }

 	# scopes
 	scope :calculo, -> (subject) { where("subject ilike ?", "%#{subject}%").order('created_at DESC')}


 	# Youtube api and validation
 	before_create -> do
	  uid = link.match(YT_LINK_FORMAT)
	  self.uid = uid[2] if uid && uid[2]
	 
	  if self.uid.to_s.length != 11
	    self.errors.add(:link, 'is invalid.')
	    false
	  elsif Video.where(uid: self.uid).any?
	    self.errors.add(:link, 'is not unique.')
	    false
	  else
	    get_additional_info
	  end
	end

	private
 
	def get_additional_info
	  begin
	    client = YouTubeIt::OAuth2Client.new(dev_key: 'AIzaSyBLso_Q9y15a5NNHfobyAVWY0JlxVIEliU')
	    video = client.video_by(uid)
	    self.title = video.title
	    self.duration = parse_duration(video.duration)
	    self.author = video.author.name
	    self.likes = video.rating.likes
	    self.dislikes = video.rating.dislikes
	  rescue
	    self.title = '' ; self.duration = '00:00:00' ; self.author = '' ; self.likes = 0 ; self.dislikes = 0
	  end
	end
	 
	def parse_duration(d)
	  hr = (d / 3600).floor
	  min = ((d - (hr * 3600)) / 60).floor
	  sec = (d - (hr * 3600) - (min * 60)).floor
	 
	  hr = '0' + hr.to_s if hr.to_i < 10
	  min = '0' + min.to_s if min.to_i < 10
	  sec = '0' + sec.to_s if sec.to_i < 10
	 
	  hr.to_s + ':' + min.to_s + ':' + sec.to_s
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update, :destroy]
	# before_action :admin_user,     only: [:create, :new]


	def new
	  @video = Video.new
	end

	def index
  	if params[:subject].present?
  		@videos = Video.calculo(params[:subject]) 
  	else
  		@videos = Video.order('created_at DESC')
  	end
	end

	def show	
    @comments = @video.comment_threads.order('created_at desc')
    @new_comment = Comment.build_from(@video, current_user.id, "") if current_user
	end
	 
	def create
	  @video = Video.new(video_params)
	  if @video.save
	    flash[:success] = 'Video added!'
	    redirect_to videos_path
	  else
	    render 'new'
	  end
	end

	def destroy
    Video.destroy(:id)
    flash[:success] = "User deleted."
    redirect_to root_path
  end

  def doubts
    @message = Message.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def doubts_mail
    @message = Message.new(doubts_message_params)

    if @message.valid?
      DoubtsMailer.new_message(@message).deliver
    else
      flash.now.alert = "Check the error list"
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

	private

		def set_user
      @video = Video.find(params[:id])
    end

    def doubts_message_params
      params.require(:message).permit(:name, :email, :subject,
                                      :body)
    end

		def video_params
			params.require(:video).permit(:link, :subject)
		end

		def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/views/videos/_thanks.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <%= image_tag 'brains_logo.png', :class => "modal-logo"%>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
      <h3>Tu duda ha sido enviada, en BrainsUniversity nos esforzamos cada día para que nuestros usuarios entiendan al 100% cada uno de nuestros videos. Gracias por hacer parte de está gran comunidad de ingenieros.</h3>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>  
  </div>
</div>

app/views/videos/doubts.js.erb
$("#modal-window").html("<%= escape_javascript(render 'shared/doubts_modal') %>");

app/views/videos/doubts_mail.js.erb
jQuery.noConflict();
$("#modal-window").modal('hide');
$("#modal-thanks").modal().html("<%= escape_javascript(render 'thanks') %>");
$("#modal-thanks").html("<%= escape_javascript(render 'thanks') %>");

app/views/videos/index.html.erb
<% if current_user %>
	<% provide(:title, current_user.name) %>
<% end %>
<div class="jumbotron">

	<% if signed_in?  %>
	  <div class="container text-center">
	    <h1>Share your videos with the world!</h1>
	    <p>Click the button below to share your video from YouTube.</p>
	    <p>
	      <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
	    </p>
	  </div>
	<% end %>

	<div class="container text-center">
		<h1>Estos son los videos que hemos recopilado para tí, escoge la materia que necesites<%= @subject %></h1>	
	</div>
   
	<div class="filter-panel">
		
		<%= link_to :controller => params[:controller], :action => params[:action], :subject => '' do%>
			<button class="btn turquoise btn-lg button-search">Todos</button> 
		<% end %>
		<%= link_to :controller => params[:controller], :action => params[:action], :subject => 'cálculo' do%>
			<button class="btn blue btn-lg button-search">Cálculo</button> 
		<% end %>
		</button>
		<%= link_to :controller => params[:controller], :action => params[:action], :subject => 'física' do%>
			<button class="btn midnight btn-lg button-search">Física</button> 
		<% end %>
		<%= link_to :controller => params[:controller], :action => params[:action], :subject => 'química' do%>
			<button class="btn purple btn-lg button-search">Química</button> 
		<% end %>
		<%= link_to :controller => params[:controller], :action => params[:action], :subject => 'algebra lineal' do%>
			<button class="btn btn-lg button-search orange">A. Lineal</button> 
		<% end %>
		
	</div>
  		
  <% if @videos.any? %>
	  <div class="container">
	    
	    <div id="player-wrapper"></div>
	 
	    <% @videos.in_groups_of(3) do |group| %>
	      <div class="row">
	        <% group.each do |video| %>
	          <% if video %>
	            <div class="col-md-4">
	              <div class="yt_video thumbnail">
	              	<a href="/videos/<%= video.id%>">
	              		<img src="https://img.youtube.com/vi/<%= video.uid %>/mqdefault.jpg" class="yt_preview img-rounded" alt= '<%=video.title %>' data-uid= 'video.uid'>
	               	</a>
	                <div class="caption">
	                  <h5><%= video.title %></h5>
	                  <p>Tema: <b><%= video.subject %></b></p>
	                  <p>Duration: <b><%= video.duration %></b></p>
	                  <p>
	                    <span class="fa fa-thumbs-up"></span> <%= video.likes %>
	                    <span class="fa fa-thumbs-down"></span> <%= video.dislikes %>
	                    <% if signed_in? && current_user.admin?  %>
										    <%= link_to "delete", video, method: :delete,
										                                  data: { confirm: "You sure?" } %>
									  	<% end %>
	                  </p>
	                </div>
	              </div>
	            </div>
	          <% end %>
	        <% end %>
	      </div>
	    <% end %>
	  </div>
	<% end %>
</div>

app/views/videos/new.html.erb
<div class="container">
  <h1 class="new-video">New video</h1>
 
  <%= form_for @video do |f| %>
    <%= render 'shared/error_messages', object: @video %>
 
    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', required: true %>
      <%= f.label :subject %>
      <%= f.text_field :subject, class: 'form-control', required: true %>
      <span class="help-block">A link to the video on YouTube.</span>
    </div>
 
    <%= f.submit class: 'btn btn-default' %>
  <% end %>
</div>

app/views/videos/show.html.erb
<% provide(:title, @video.title) %>
<section id="video-list">
	<div class="container">
    <div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
    <div id="modal-thanks" class="modal fade" role="dialog" aria-labelledby="myModalLabels" aria-hidden="true"></div>
		<div class="video-player">
			<%= youtube_embed(@video.link) %>	
      <%= link_to doubts_path(@video.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', 'data-dev' => "#{@video.title}"} do %>
        <button type="button" class="btn btn-primary"> Escríbenos tus dudas </button>                
      <% end %>
		</div>
    <div class="comments">
      <h2>Comentarios</h2>
      <% if current_user %>
        <%= render :partial => 'comments/form', :locals => { :comment => @new_comment } %>
      <% end %>
      <%= render :partial => 'comments/comment', :collection => @comments, :as => :comment %>
    </div>
	</div>	
</section>