config/routes.rb
BrainsUniversity::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :videos, only: [:index, :new, :create, :show]
  resources :comments, :only => [:create, :destroy]
  
  scope :module => "materias" do
    get 'materias', to: 'materias#index', as: '/materias'
    
    resources :estatica, only: [:index] do
      collection do
        get 'equilibrio_cuerpos_rigidos'
      end
    end
    
    resources :termodinamica, only: [:index]
  end

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/users',   to: 'users#show',           via: 'get'
  match '/videos',  to: 'user#index',           via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/landing', to: 'static_pages#landing', via: 'get'
  match '/home',    to: 'static_pages#home', via: 'get'
  

  get "videos/:id/doubts" => 'videos#doubts', :as => :doubts
  post "videos/doubts_mail" => 'videos#doubts_mail', :as => :doubts_mail
  match '/contact',  to: 'static_pages#create',        via: 'post'

  root 'static_pages#home'

  

end

app/views/shared/_doubts_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Escribenos tus dudas acerca del ejercicio, recuerda escribir tu duda de la mejor manera para poder ofrecerte nuestra ayuda oportuna. </h3>
    </div>
    <div class="modal-body">
      <div class="col-xs-12">

        <%= form_for @message, remote: true, url: doubts_mail_path ,:html => { :class => 'contact doubts-form'} do |f| %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.label :name do %>
                Tu nombre <b class="required"></b>
              <% end %>
              <%= f.text_field :name, :required => true, placeholder: "Pepito Perez" %>
            </div>
            <div class="col-xs-6">
              <%= f.label :email do %>
                Tu correo <b class="required"></b>
              <% end %>
              <%= f.text_field :email, :required => true, placeholder: "John@Stuart.com"%>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <%= f.label :body do %>
                Escribe tu duda <b class="required"></b>
              <% end %>
              <%= f.text_area :body, :required => true, rows: 4, placeholder: "Ej: En que situaciones se aplica torque en un punto dado?..." %>
            </div>
          </div>
          <div class="actions">
            <%= f.submit 'Send', class: 'btn btn-primary', data: {disable_with: "Sending..."} %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>  
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      El formulario contiene <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>