config/routes.rb
BrainsUniversity::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :videos, only: [:index, :new, :create, :show]
  resources :comments, :only => [:create, :destroy]
  
  scope :module => "materias" do
    get 'materias', to: 'materias#index', as: '/materias'
    
    resources :estatica, only: [:index] do
      collection do
        get 'equilibrio_cuerpos_rigidos'
      end
    end
    
    resources :termodinamica, only: [:index]
  end

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/users',   to: 'users#show',           via: 'get'
  match '/videos',  to: 'user#index',           via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/landing', to: 'static_pages#landing', via: 'get'
  match '/home',    to: 'static_pages#home', via: 'get'
  

  get "videos/:id/doubts" => 'videos#doubts', :as => :doubts
  post "videos/doubts_mail" => 'videos#doubts_mail', :as => :doubts_mail
  match '/contact',  to: 'static_pages#create',        via: 'post'

  root 'static_pages#home'

  

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69337611-1', 'brainsuniversity.com');
  ga('set', '&uid', 'current_user'); // Establezca el ID de usuario mediante el user_id con el que haya iniciado sesión.
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<!-- Le Footer -->    
<footer class="footer-wrapper hidden-xs">
  <div class="footer-links container">
    <div class="row">
      <div class="col-sm-4 top">
        <ul>
          <li>
            <a class="underline"href="/signup"> Crea una cuenta gratis </a>    
          </li>
          <li>
            <a href="/modulos"> Nuestros Módulos </a>    
          </li>
          <li>
            <a href="#"> Mira nuestros planes </a> 
          </li>
          <li>
            <a href="#"> Ayuda </a>      
          </li>
          <li>
            <a href="#"> Nuestro Blog </a>      
          </li>
        </ul>
      </div>
      <div class="col-sm-4 top">
        <h4>Síguenos en nuestras redes</h4>
        <div class="social row">
          <div><a target="_blank" href="https://www.facebook.com/brainsuniversityco/"> <i class="fa fa-facebook fa-3"></i> </a></div>
          <div><a target="_blank" href="https://www.youtube.com/channel/UCHjmu5ieXyUXehFRWFaKkTQ"> <i class="fa fa-youtube fa-3"></i> </a> </div>
          <div><a target="_blank" href="https://twitter.com/BrainsUni"> <i class="fa fa-twitter fa-4"></i> </a></div>
          <div><a target="_blank" href="https://instagram.com/brainsuniversity/"> <i class="fa fa-instagram fa-4"></i> </a></div>
        </div>
      </div>
      <div class="col-sm-4 glass">
        <%= image_tag('brain.png') %>
      </div>
    </div>
  </div>
</footer>

<div class="footer-copyright">
  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        &copy; BrainsUniversity. All Rights Reserved.
      </div>
      <div class="col-sm-4 text-right mobile-center">
        La verdad os hará libres - Jesús
      </div>
    </div>
  </div>
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <!-- Gmail Validation Meta-->
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  
  <meta name="google-site-verification" content="DZBV29_3nAehejcEOjqfcua_vgqZvOfblDU19S2G4HQ" />

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">

  <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,100italic,100&subset=all' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Duru+Sans&subset=all' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Amaranth:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Youtube api -->
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript" src="https://www.youtube.com/iframe_api"></script>

  <!-- fonts -->
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <!-- Le CSS
    ================================================== -->
  <%= stylesheet_link_tag    "picons" %>
  <%= stylesheet_link_tag    "style" %>
  
  <!-- Js -->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <%= javascript_include_tag "modernizr.custom" %>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  

  <!-- Add mousewheel plugin (this is optional) -->
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  
</head>

<body id="top">

  
    <nav>
      <div class="container">
        <div class="logo pull-left col-xs-4">
          <a class="home_link" href="/">
            <img src="/assets/brains_logo.png" alt="Main Logo" >
          </a>  
        </div>
        <ul class="col-xs-8 navbar-right" id="top-menu">
          <% if !signed_in? %>
            <li class="videos">
              <%= link_to 'Ingresar', signin_path %>
            </li>
          <% else %>
            <li>
              <%= link_to signout_path, method: "delete" do %>
                Salir
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_path(current_user) do %>
                <%= @current_user.name.split[0..1].join(' ') %>
              <% end %>
            </li>
          <% end %>
          <li><a href="/materias"> Materias</a></li>
          <li><a href="/contact">  Contactos</a></li>
        </ul>    
      </div>
    </nav>
  
  <%= yield %>

  <% if signed_in? %>
  
    <% if !current_page?(root_path) && !current_page?('/signin') && !current_page?('/signup') && !current_page?(edit_user_path(current_user))%>
      <%= render 'layouts/footer' %>
    <% end %>
  <% else %>

    <% if !current_page?('/signin') && !current_page?('/signup') %>
      <%= render 'layouts/footer' %>
    <% end %>
  <% end %>
        
  <%= render 'layouts/analytics' %>
</body>
</html>